const {app,BrowserWindow,ipcMain}=require('electron');const fs=require('fs');const path=require('path');const {createEntryStore}=require('../electron/entries-store.cjs');
const profile=path.resolve(__dirname,'../release/EntriesTest-'+Date.now());app.setPath('userData',profile);const store=createEntryStore(path.join(profile,'entries.json'));
ipcMain.handle('world:load',()=>null);ipcMain.handle('world:save',()=>true);ipcMain.handle('entries:load',()=>store.load());ipcMain.handle('entries:save',(_,d,r)=>store.save(d,r));
app.whenReady().then(async()=>{try{const win=new BrowserWindow({width:1480,height:980,show:false,webPreferences:{preload:path.resolve(__dirname,'../electron/preload.cjs'),contextIsolation:true,sandbox:true}});let errors=[];win.webContents.on('console-message',(_e,level,message)=>{if(level===3)errors.push(message)});await win.loadFile(path.resolve(__dirname,'../index.html'));await new Promise(r=>setTimeout(r,300));
 const result=await win.webContents.executeJavaScript(`(async()=>{const check=(b,m)=>{if(!b)throw Error(m)};const wait=()=>new Promise(r=>setTimeout(r,200));document.querySelector('[data-go="cards"]').click();check(document.querySelectorAll('.entity-card').length===108,'108 entity cards');const search=q=>{const i=document.querySelector('#entry-search');i.value=q;i.dispatchEvent(new Event('input',{bubbles:true}));};search('伊维娅');const snow=[...document.querySelectorAll('.entity-card')].find(x=>x.querySelector('h2').textContent==='洛星雪');check(snow,'alias search');snow.click();document.querySelector('#entry-edit').click();const form=document.querySelector('#entry-form');const expectedPreview=document.createElement('div');expectedPreview.innerHTML=ArchiveView.markdown(form.elements.body.value);check(document.querySelector('#entry-body-preview').innerHTML===expectedPreview.innerHTML,'initial preview');const originalBody=form.elements.body.value;form.elements.body.value=['# 实时标题','**即时加粗**','<img src=x onerror=alert(1)>'].join(String.fromCharCode(10));form.elements.body.dispatchEvent(new Event('input',{bubbles:true}));const preview=document.querySelector('#entry-body-preview');check(preview.querySelector('h2')?.textContent==='实时标题','live heading before save');check(preview.querySelector('strong')?.textContent==='即时加粗','live bold before save');check(!preview.querySelector('img')&&preview.textContent.includes('<img'),'preview escapes HTML');form.elements.body.value=originalBody;form.elements.body.dispatchEvent(new Event('input',{bubbles:true}));form.elements.summary.value='本机持久化验证';form.elements.tags.value='测试标签';form.elements.body.value+='\\n\\n独特检索标记 <img src=x onerror=alert(1)>';form.requestSubmit();await wait();check(!document.querySelector('#entry-editor').open,'saved and closed');check(document.querySelector('.entry-lead').textContent==='本机持久化验证','summary persisted');check(!document.querySelector('.entry-detail img'),'safe edited content');search('独特检索标记');check(document.querySelectorAll('.entity-card').length===1,'edited body searchable');document.querySelector('[data-entry-source]').click();check(document.querySelector('#entry-source').open,'source link');document.querySelector('#source-close').click();document.querySelector('#entry-new').click();const f=document.querySelector('#entry-form');f.elements.title.value='测试新词条';f.elements.body.value='新的地点设定';f.elements.type.value='地点';f.requestSubmit();await wait();check(document.querySelector('.entry-detail-head h2').textContent==='测试新词条','create');return 'Live Markdown preview, create, edit, alias/body search, escaping and source links passed';})()`);
 await win.loadFile(path.resolve(__dirname,'../index.html'));await new Promise(r=>setTimeout(r,300));await win.webContents.executeJavaScript(`(()=>{document.querySelector('[data-go="cards"]').click();if(document.querySelectorAll('.entity-card').length!==109)throw Error('reload count');const card=[...document.querySelectorAll('.entity-card')].find(x=>x.querySelector('h2').textContent==='洛星雪');card.click();if(document.querySelector('.entry-lead').textContent!=='本机持久化验证')throw Error('reload lost edits');})()`);
 const persisted=await store.load();if(persisted.storeRevision!==2)throw Error('Disk store revisions');
 // Capture the seeded UI in a fresh test window, without test content.
 ipcMain.removeHandler('entries:load');ipcMain.handle('entries:load',()=>null);await win.loadFile(path.resolve(__dirname,'../index.html'));await new Promise(r=>setTimeout(r,300));await win.webContents.executeJavaScript(`document.querySelector('[data-go="cards"]').click();document.querySelector('#entry-type').value='人物';document.querySelector('#entry-type').dispatchEvent(new Event('change',{bubbles:true}));[...document.querySelectorAll('.entity-card')].find(x=>x.querySelector('h2').textContent==='洛星雪').click();`);await new Promise(r=>setTimeout(r,400));fs.writeFileSync(path.resolve(__dirname,'../Design/entries-implemented.png'),(await win.webContents.capturePage()).toPNG());fs.writeFileSync(path.resolve(__dirname,'../release/entries-test-result.txt'),result+'; actual disk reload passed.');console.log(result);app.exit(0);}catch(e){fs.writeFileSync(path.resolve(__dirname,'../release/entries-test-result.txt'),String(e.stack));console.error(e);app.exit(1);}});

