const test=require('node:test'),assert=require('node:assert/strict'),F=require('../src/relations-force.js');
test('degree increases repulsion; dragging fixes node',()=>{const a=F.create([{id:'a'},{id:'b'}],[],{a:{x:550,y:400},b:{x:650,y:400}}),b=structuredClone(a);b.byId=new Map(b.nodes.map(n=>[n.id,n]));b.nodes[0].degree=4;F.step(a);F.step(b);assert.ok(Math.abs(b.nodes[1].vx)>Math.abs(a.nodes[1].vx));const x=b.nodes[0].x;F.step(b,'a');assert.equal(b.nodes[0].x,x);});
test('coincident nodes stay finite and settle',()=>{const sim=F.create(Array.from({length:108},(_,i)=>({id:String(i)})),[['0','1'],['0','2']],{});for(let i=0;i<1500;i++)F.step(sim);for(const n of sim.nodes){assert.ok(Number.isFinite(n.x)&&Number.isFinite(n.y));assert.ok(Math.hypot(n.vx,n.vy)<1);}const overlap=F.create([{id:'a'},{id:'b'}],[],{a:{x:0,y:0},b:{x:0,y:0}});F.step(overlap);assert.ok(overlap.nodes.every(n=>Number.isFinite(n.x)));});

test('no global attraction; linked node approaches persistent pin',()=>{const s=F.create([{id:'a'}],[],{a:{x:50,y:60}});F.step(s);assert.equal(s.nodes[0].x,50);assert.equal(s.nodes[0].y,60);const p=F.create([{id:'a'},{id:'b'}],[['a','b']],{a:{x:10,y:10,pinned:true},b:{x:2000,y:10}});F.step(p);assert.equal(p.nodes[0].x,10);assert.ok(p.nodes[1].x<2000);});

test('force cutoff and smooth tail',()=>{const make=d=>F.create([{id:'a'},{id:'b'}],[],{a:{x:0,y:0},b:{x:d,y:0}});const far=make(F.range+1);F.step(far);assert.equal(far.nodes[0].vx,0);assert.equal(far.nodes[1].vx,0);const near=make(F.range-1);F.step(near);assert.ok(near.nodes[0].vx<=0);const inside=make(F.range-30);F.step(inside);assert.ok(inside.nodes[0].vx<0);assert.ok(Math.abs(near.nodes[0].vx)<.001);});

test('outside range stops immediately even with momentum',()=>{const s=F.create([{id:'a'},{id:'b'}],[],{a:{x:0,y:0},b:{x:F.range+1,y:0}});s.nodes[0].vx=-6;s.nodes[1].vx=6;s.nodes[0].vy=3;F.step(s);assert.equal(s.nodes[0].x,0);assert.equal(s.nodes[0].y,0);assert.equal(s.nodes[1].x,F.range+1);assert.equal(s.nodes[0].vx,0);});

test('linked pairs settle closer without overlap or unrelated attraction',()=>{const make=edges=>F.create([{id:'a'},{id:'b'}],edges,{a:{x:0,y:0},b:{x:300,y:0}});const linked=make([['a','b']]),apart=make([]);for(let i=0;i<1200;i++){F.step(linked);F.step(apart);}const d=linked.nodes[1].x-linked.nodes[0].x;assert.ok(d>=94&&d<120);assert.equal(apart.nodes[1].x-apart.nodes[0].x,300);assert.ok(Math.abs(linked.nodes[0].vx)<.02);});

test('dragged group stays under pointer while neighbors react',()=>{const s=F.create([{id:'a'},{id:'b'},{id:'c'},{id:'d'}],[['a','b']],{a:{x:0,y:0},b:{x:250,y:0},c:{x:-70,y:0},d:{x:0,y:150}});F.step(s,new Set(['a','d']));assert.equal(s.byId.get('a').x,0);assert.equal(s.byId.get('d').y,150);assert.ok(s.byId.get('b').x<250);assert.ok(s.byId.get('c').x<-70);});
