const modules=[['home','⌂','首页'],['overview','◈','世界概览'],['cards','▤','设定卡片'],['timeline','◷','时间线'],['map','⌖','世界地图'],['relations','⌘','关系图'],['gallery','▧','插图集'],['archive','▥','来源档案'],['templates','▱','提案模板']];
let tasks=[];try{const saved=JSON.parse(CloudState.getItem('kuat-tasks-v1')||'[]');if(Array.isArray(saved)&&saved.every(t=>typeof t.text==='string'&&typeof t.done==='boolean'))tasks=saved;}catch{}
let world=structuredClone(WorldModel.initial), active='home';
const $=s=>document.querySelector(s); const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function render(){
 document.body.classList.toggle('relations-view',active==='relations');
 document.body.classList.toggle('home-view',active==='home');
 document.body.classList.toggle('archive-view',['cards','archive','relations','timeline'].includes(active));
 $('#navigation').innerHTML=modules.map(([id,icon,label])=>`<button data-page="${id}" class="nav-item ${id===active?'active':''}"><span>${icon}</span>${label}${id===active?'<i></i>':''}</button>`).join('')+'<p class="nav-label future-label">未来工作区</p><div class="disabled-nav">⌬ <span>世界模拟</span><small>规划中</small></div><div class="disabled-nav">♧ <span>共创</span><small>暂缓</small></div>';
 $('#crumb').textContent=modules.find(x=>x[0]===active)[2];const canEditOverview=Boolean(window.KuatAccess?.write?.includes('world'));$('#edit').hidden=active!=='overview'||!canEditOverview;
 $('#main').innerHTML=active==='home'?home():active==='overview'?overview():active==='cards'?EntriesView.render():active==='archive'?ArchiveView.render():active==='relations'?RelationsView.render():active==='timeline'?TimelineView.render():active==='templates'?templateStudio():placeholder();
 if(active==='timeline')TimelineView.afterRender();
 $('#outline').innerHTML=active==='overview'?'<a href="#background" class="outline-link">01 <span>世界背景</span></a><a href="#calendar" class="outline-link">02 <span>世界历法</span></a><a href="#concept" class="outline-link">03 <span>世界概念</span></a>':'<p class="muted">模块建设中</p>';
 $('#activities').innerHTML=world.changes.length?world.changes.slice(0,5).map(c=>`<div class="activity"><i></i><div>${escape(c.text)}<small>白羽奈绪 · ${date(c.at)}</small></div></div>`).join(''):'<div class="empty-activity">还没有编辑记录<br><small>保存一次概览，记录便从这里开始。</small></div>';
 $('#sync-status').textContent=world.pendingSync?'● 有待同步的设定更新':'同步通道尚未接入';
 $('#save-state').textContent=world.updatedAt?'已保存 · '+date(world.updatedAt):'云端档案';
}
function activityList(){return world.changes.length?world.changes.slice(0,4).map(c=>`<button class="recent-row" data-go="overview"><span class="tile-icon">▤</span><span><strong>${escape(c.text)}</strong><small>${date(c.at)}</small></span><b>›</b></button>`).join(''):'<div class="empty-state">暂无变更记录<small>编辑并保存世界概览后，记录会显示在这里。</small></div>';}
function home(){const descriptions=['查看背景与基础概念','编辑、查询与连接设定','梳理事件与时代','管理空间与地点','连接人物与设定','整理视觉参考'];return `<div class="home-heading"><h1>首页</h1><p>${new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'})}</p></div><div class="home-grid"><div class="home-primary"><section class="home-banner"><div><h2>${escape(world.name)}</h2><p>世界构建项目</p><div class="banner-tags"><span>♧ 私有项目</span><span>● 构建中</span></div><button class="primary" data-go="overview">打开世界概览 →</button></div></section><section class="home-panel"><h2>继续工作</h2><button class="recent-row" data-go="overview"><span class="tile-icon">▤</span><span><strong>世界背景 · 概览</strong><small>${world.updatedAt?'修改于 '+date(world.updatedAt):'打开概览，开始整理世界设定'}</small></span><b>›</b></button></section><section class="home-panel"><h2>世界内容</h2><div class="content-grid">${modules.slice(1,7).map(([id,icon,label],i)=>`<button class="content-tile" data-go="${id}"><span class="tile-icon">${icon}</span><span><strong>${label}</strong><small>${descriptions[i]}</small>${id==='cards'?'<em>'+IDEAArchive.documents.length+' 份已归档</em>':!['overview','relations','timeline'].includes(id)?'<em>待开发</em>':''}</span><b>›</b></button>`).join('')}</div></section></div><div class="home-secondary"><section class="home-panel"><div class="home-panel-heading"><h2>当前事项</h2><button class="quiet" id="add-task" aria-label="添加事项">＋</button></div><div id="task-list">${tasks.length?tasks.map((t,i)=>`<label class="task-row"><input type="checkbox" data-task="${i}" ${t.done?'checked':''}><span class="${t.done?'done':''}">${escape(t.text)}</span></label>`).join(''):'<div class="empty-state">还没有待办事项<small>点击右上角 ＋ 添加需要跟进的内容。</small></div>'}</div><form id="task-form" hidden><input id="task-input" aria-label="事项内容" placeholder="输入事项，按回车添加" maxlength="120" required><button class="primary" type="submit">添加</button></form></section><section class="home-panel"><h2>最近变更</h2>${activityList()}</section><section class="home-panel home-sync"><h2>Matrees 状态</h2><div class="sync-summary"><span class="tile-icon">☁</span><div><strong>未接入同步</strong><p>${world.pendingSync?'有云端设定更新等待同步。':'当前为云端工作区。'}</p></div></div><button data-sync>导出待同步内容</button><small>导出不会自动更新 Matrees</small></section></div></div><footer class="canvas-footer"><span>云端工作区 / Project World</span><span>K.U.A.T · 0.1.0</span></footer>`;}
function overview(){return `<section class="page-heading"><div><h1>世界概览</h1><p>背景档案与核心设定</p></div><span class="outline-badge">私有文档</span></section><section class="panel" id="background"><div class="panel-title"><h2>世界背景</h2><button class="text-button" data-edit>编辑</button></div><h2 class="document-title">${escape(world.name)}</h2><p class="document-subtitle">${escape(world.subtitle)}</p><p class="prose">${escape(world.background)}</p><div class="hero-tags">${world.tags.map(t=>`<span>${escape(t)}</span>`).join('')}</div></section><section class="panel" id="calendar"><div class="panel-title"><h2>世界历法</h2><button class="text-button" data-go="timeline">打开时间线 ↗</button></div><div class="calendar-empty"><span class="calendar-symbol">◷</span><div><h3>${escape(TimelineView.summary())}</h3><p>在时间线中设置历法、添加事件并安排时间。</p></div></div></section><section class="panel" id="concept"><div class="panel-title"><h2>世界概念</h2></div><div class="concept-content"><span class="concept-icon">✧</span><p class="prose">${escape(world.concept)}</p></div></section>`;}
function templateStudio(){const defaults={title:{x:28,y:24,w:620,h:38,size:24,opacity:1},subtitle:{x:28,y:70,w:500,h:24,size:12,opacity:.8},name:{x:28,y:130,w:560,h:48,size:20,opacity:1},type:{x:28,y:192,w:260,h:40,size:14,opacity:1},category:{x:310,y:192,w:260,h:40,size:14,opacity:1},body:{x:28,y:260,w:700,h:220,size:14,opacity:1},actions:{x:28,y:510,w:700,h:48,size:14,opacity:1}};let cfg;try{cfg=JSON.parse(CloudState.getItem('kuat-template-proposal-v1')||'null')||defaults;}catch{cfg=defaults;}let selected='title';const labels={title:'顶部标题',subtitle:'自动保存状态',name:'设定名称',type:'类型',category:'设定分类',body:'正文编辑区',actions:'底部操作栏'};const paint=()=>Object.entries(labels).map(([id,label])=>{const c=cfg[id];return `<button class="template-element ${id===selected?'selected':''}" data-template-select="${id}" style="left:${c.x}px;top:${c.y}px;width:${c.w}px;height:${c.h}px;font-size:${c.size}px;opacity:${c.opacity}">${label}</button>`}).join('');const inspector=()=>{const c=cfg[selected];return `<aside class="template-inspector"><h2>模板属性</h2><p class="muted">${labels[selected]}</p>${[['x','横坐标'],['y','纵坐标'],['w','宽度'],['h','高度'],['size','字号'],['opacity','透明度']].map(([k,l])=>`<label>${l}<input type="number" step="${k==='opacity'?'.05':'1'}" min="${k==='opacity'?'0':'0'}" max="${k==='opacity'?'1':'2000'}" data-template-prop="${k}" value="${c[k]}"></label>`).join('')}<button class="primary" id="template-save">保存模板</button><small>模板用于设定、事件等编辑器；保存后可继续调整。</small></aside>`};return `<section class="page-heading"><div><h1>提案模板</h1><p>可视化调整通用编辑器布局</p></div></section><div class="template-studio"><div class="template-canvas" id="template-canvas">${paint()}</div>${inspector()}</div>`;}function placeholder(){const m=modules.find(x=>x[0]===active);return `<section class="page-heading"><div><div class="section-kicker">PROJECT WORLD WORKSPACE</div><h1>${m[2]}</h1><p>世界创作工作台的一部分。</p></div></section><div class="module-empty"><span>${m[1]}</span><h2>${m[2]}，即将开始构建</h2><p>当前版本先实现世界概览。这个模块已预留位置，尚未提供编辑功能。</p><button class="primary" data-go="overview">返回世界概览</button></div>`;}
$('#navigation').onclick=e=>{const b=e.target.closest('[data-page]');if(b){active=b.dataset.page;render();window.scrollTo(0,0);}};
$('#main').onclick=e=>{const b=e.target.closest('[data-go]');if(b){active=b.dataset.go;render();window.scrollTo(0,0);}if(e.target.closest('[data-edit]'))$('#edit').click();if(e.target.closest('[data-sync]'))download(true);if(e.target.closest('#add-task')){$('#task-form').hidden=false;$('#task-input').focus();}};
$('#main').addEventListener('submit',e=>{if(e.target.id!=='task-form')return;e.preventDefault();const text=$('#task-input').value.trim();if(!text)return;const next=[...tasks,{text,done:false}];try{CloudState.setItem('kuat-tasks-v1',JSON.stringify(next));tasks=next;render();}catch{toast('事项保存失败，请检查云端连接');}});
$('#main').addEventListener('change',e=>{if(!e.target.matches('[data-task]'))return;const next=tasks.map((t,i)=>i===Number(e.target.dataset.task)?{...t,done:e.target.checked}:t);try{CloudState.setItem('kuat-tasks-v1',JSON.stringify(next));tasks=next;render();}catch{e.target.checked=!e.target.checked;toast('事项保存失败');}});
$('.brand').onclick=e=>{e.preventDefault();active='home';render();};
$('#edit').onclick=()=>{const f=$('#edit-form');for(const k of ['name','subtitle','background','concept'])f.elements[k].value=world[k];f.elements.tags.value=world.tags.join('，');$('#editor').showModal();};
$('#close').onclick=()=>$('#editor').close();
$('#edit-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const fields=Object.fromEntries(f);fields.tags=fields.tags.split(/[,，]/).map(x=>x.trim()).filter(Boolean);const next=WorldModel.update(world,fields);try{if(window.kuat)await window.kuat.save(next);else CloudState.setItem('kuat-world-v1',JSON.stringify(next));world=next;$('#editor').close();render();toast('概览已保存，更新已标记为待同步');}catch{toast('云端保存失败，请检查连接后重试');}};
function download(sync=false){const data=sync?{type:'matrees-manual-sync',exportedAt:new Date().toISOString(),target:'https://matrees.cn/world/overview?worldId=1922648981268111360',status:'pending',world}:world;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=sync?'Project-World-待同步.json':'Project-World-档案.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(sync?'已导出待同步内容，尚未更新 Matrees':'世界概览已导出（不含设定资料库）');}
$('#export').onclick=()=>download();$('#sync-export').onclick=()=>download(true);
(async()=>{try{const saved=window.kuat?await window.kuat.load():JSON.parse(CloudState.getItem('kuat-world-v1')||'null');if(saved)world=WorldModel.validate(saved);}catch{toast('现有档案无法读取，显示初始内容；原数据未自动覆盖');}$('#storage-kind').textContent=window.kuat?'数据保存在云端档案':'数据保存在云端';render();})();
// Stop decorative animation while the app is hidden; editing pauses Core via CSS.
document.addEventListener('visibilitychange',()=>document.body.classList.toggle('motion-paused',document.hidden));

ArchiveView.install(render);

EntriesView.install(render,toast);

RelationsView.install(render,page=>{active=page;render();},toast);

TimelineView.install(render,toast);

