/* Creative data lives on the server. This module keeps only a runtime memory copy. */
const CloudState=(()=>{
 let docs={},state={},timer,queue=Promise.resolve(),dirty=false,blocked=false,role='reader',saving=0,leaving=false;
 const status=text=>{document.querySelector('#cloud-status').textContent=text;};
 function fail(error){blocked=true;status('云端保存失败 · 请勿关闭');const d=document.querySelector('#cloud-error');d.querySelector('p').textContent=error.message+'。未保存的内容仅在当前窗口内存中。';if(!d.open)d.showModal();}
 async function save(name,data){if(blocked)throw Error('云端连接异常，请先重试保存');if(!window.KuatAccess.write.includes(name))throw Error('当前级别无权修改此模块');saving++;try{const next=await window.kuatCloud.save(name,data,docs[name]?.revision||0);docs[name]=next;return structuredClone(next.data);}finally{saving--;}}
 async function flush(){clearTimeout(timer);const pending=queue.then(async()=>{if(!dirty)return;const snapshot=structuredClone(state);dirty=false;status('正在保存云端…');try{await save('state',snapshot);status('云端已保存');}catch(e){dirty=true;fail(e);throw e;}});queue=pending.catch(()=>{});return pending;}
 async function leave(){leaving=true;try{await flush();while(saving)await new Promise(r=>setTimeout(r,25));}catch(e){leaving=false;throw e;}}
 const api={leave,cancelLeave:()=>{leaving=false;},getItem:k=>state[k]??null,setItem:(k,v)=>{if(leaving)return;if(blocked)throw Error('云端保存已暂停');if(!window.KuatAccess.write.includes('state'))throw Error('当前级别无权编辑画布或待办');if(state[k]===v)return;state[k]=v;dirty=true;status('正在保存云端…');clearTimeout(timer);timer=setTimeout(()=>flush().catch(()=>{}),600);},save,flush,
 load:async()=>{const result=await window.kuatCloud.load();window.kuatRole=result.role;window.KuatAccess={...result.permissions,rank:result.rank,ranks:result.ranks,username:result.username};const rank=result.ranks.find(r=>r.id===result.rank);const profileName=document.querySelector('#profile-username'),profileRank=document.querySelector('#profile-rank'),profileAvatar=document.querySelector('#profile-avatar');if(profileName)profileName.textContent=result.username;if(profileRank)profileRank.textContent=`${rank?.alias||result.rank} · ${rank?.name||''}`;if(profileAvatar)profileAvatar.textContent=(rank?.alias||result.rank).slice(0,1);docs=result.documents;role=result.role;for(const name of ['world','entries','timeline','state','archive'])if(!docs[name])throw Error('云端档案尚未初始化：'+name);state=structuredClone(docs.state.data);return docs;}};
 window.addEventListener('beforeunload',e=>{if(dirty||saving){e.preventDefault();e.returnValue='仍有未保存的云端修改';flush().catch(()=>{});}});
 document.addEventListener('click',e=>{if(e.target.closest('#cloud-retry')){blocked=false;flush().then(()=>document.querySelector('#cloud-error').close()).catch(()=>{});}if(e.target.closest('#cloud-reload')&&confirm('放弃尚未保存的修改并重新登录？')){dirty=false;location.reload();}});
 return api;
})();
(async()=>{
 const dialog=document.querySelector('#cloud-login'),form=document.querySelector('#cloud-login-form'),error=document.querySelector('#cloud-login-error');
 dialog.addEventListener('cancel',e=>e.preventDefault());document.querySelector('#cloud-error').addEventListener('cancel',e=>e.preventDefault());document.body.classList.add('auth-active');dialog.showModal();
 let setup=false;
 async function enter(animate=true){
 const docs=await CloudState.load();
 window.IDEAArchive=docs.archive.data;window.KUATEntrySeed=docs.entries.data;
 window.kuat={load:async()=>structuredClone(docs.world.data),save:data=>CloudState.save('world',data),loadEntries:async()=>structuredClone(docs.entries.data),saveEntries:async data=>{const next={...data,storeRevision:(data.storeRevision||0)+1};return CloudState.save('entries',next);},loadTimeline:async()=>structuredClone(docs.timeline.data),saveTimeline:async data=>CloudState.save('timeline',{...data,storeRevision:data.storeRevision+1})};
 for(const file of ['model','archive','entries-model','entries','relations-force','relations','timeline-model','timeline','app'])await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='src/'+file+'.js';s.onload=resolve;s.onerror=()=>reject(Error('加载模块失败'));document.body.append(s);});if(animate){dialog.classList.add('auth-leaving');await new Promise(r=>setTimeout(r,matchMedia('(prefers-reduced-motion: reduce)').matches?0:500));const welcome=window.KuatTerminal.welcome();dialog.close();await welcome;}else{dialog.close();}document.body.classList.remove('auth-active');installAccountControls();document.querySelector('#cloud-status').textContent='云端已连接';
 }
 const retry=document.createElement('button');retry.type='button';retry.textContent='重试自动登录';retry.hidden=true;form.append(retry);
 async function resume(){form.querySelector('button').disabled=true;retry.disabled=true;try{error.textContent='正在恢复登录…';if(await window.kuatCloud?.resume?.()){await enter(false);}error.textContent='';retry.hidden=true;}catch(e){error.textContent='自动登录暂未成功：'+e.message;retry.hidden=false;}finally{form.querySelector('button').disabled=false;retry.disabled=false;}}
 retry.onclick=resume;
 form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;error.textContent='正在认证…';try{if(!window.kuatCloud)throw Error('请使用桌面软件连接云端');if(setup){await window.kuatCloud.setup(form.elements.email.value,form.elements.password.value);setup=false;document.querySelector('#cloud-setup-note').hidden=true;}await window.kuatCloud.login(form.elements.email.value,form.elements.password.value);form.elements.password.value='';error.textContent='认证通过，正在载入工作区…';await enter();}catch(e){error.textContent=e.message;}finally{b.disabled=false;}};
 try{setup=await window.kuatCloud?.setupAvailable?.()||false;if(setup){document.querySelector('#cloud-setup-note').hidden=false;form.querySelector('button').textContent='初始化管理员并登录';}else await resume();}catch(e){error.textContent=e.message;}
})();

function installAccountControls(){
 const logout=document.createElement('button');logout.textContent='退出登录';document.querySelector('.top-actions').append(logout);logout.onclick=async()=>{logout.disabled=true;try{await CloudState.leave();await window.kuatCloud.logout();document.body.classList.add('session-leaving');await new Promise(r=>setTimeout(r,matchMedia('(prefers-reduced-motion: reduce)').matches?0:450));location.reload();}catch(e){document.body.classList.remove('session-leaving');CloudState.cancelLeave();alert('未能退出：'+e.message);logout.disabled=false;}};
 const profile=document.querySelector('.profile');const profileDialog=document.createElement('dialog');profileDialog.id='profile-dialog';profileDialog.innerHTML='<form><div class="dialog-head"><h2>个人资料</h2><button type="button" data-profile-close>关闭</button></div><label>昵称<input name="nickname" maxlength="80"></label><label>签名<textarea name="signature" rows="3" maxlength="200"></textarea></label><label>头像标识<input name="avatar" maxlength="4" placeholder="例如：Ω"></label><p data-profile-message role="status"></p><button class="primary">保存个人资料</button></form>';document.body.append(profileDialog);profile?.addEventListener('click',async()=>{try{const v=await window.kuatCloud.profile();const f=profileDialog.querySelector('form');f.nickname.value=v.nickname||'';f.signature.value=v.signature||'';f.avatar.value=v.avatar||'';profileDialog.showModal();}catch(e){alert(e.message);}});profileDialog.addEventListener('click',e=>{if(e.target.matches('[data-profile-close]'))profileDialog.close();});profileDialog.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button.primary');b.disabled=true;try{const v=await window.kuatCloud.updateProfile(f.nickname.value,f.signature.value,f.avatar.value);document.querySelector('#profile-username').textContent=v.nickname||v.username;document.querySelector('#profile-avatar').textContent=v.avatar||v.username.slice(0,1);document.querySelector('#profile-rank').title=v.signature||'';profileDialog.close();}catch(err){f.querySelector('[data-profile-message]').textContent=err.message;}finally{b.disabled=false;}});
 const ranks=window.KuatAccess.ranks;const rankName=id=>{const r=ranks.find(x=>x.id===id);return r?`${r.name} · ${r.id} (${r.alias})`:id;};const toolbar=document.querySelector('.top-actions');const badge=document.createElement('span');badge.className='kuat-rank-badge';badge.textContent=rankName(window.KuatAccess.rank);badge.style.setProperty('--rank-color',ranks.find(x=>x.id===window.KuatAccess.rank)?.color||'#9098a5');badge.title='可编辑：'+(window.KuatAccess.write.join(' / ')||'只读')+'；账号发放权限单独授予空间所有者';toolbar.prepend(badge);const button=document.createElement('button');button.textContent=window.kuatRole==='owner'?'账号管理':'修改密码';toolbar.prepend(button);
 const d=document.createElement('dialog');document.body.append(d);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function open(){try{const rows=window.kuatRole==='owner'?(await window.kuatCloud.accounts()).accounts:[];d.innerHTML=`<div class="dialog-head"><h2>账号管理</h2><button id="account-close">关闭</button></div>${window.kuatRole==='owner'?`<h3>发放账号</h3><form id="issue-account"><label>账号<input name="username" required pattern="[A-Za-z0-9_.@-]{3,80}"></label><label>初始密码<input name="password" type="password" required autocomplete="new-password"></label><label>K.U.A.T 级别<select name="role">${ranks.map(r=>`<option value="${r.id}" ${r.id==='Green'?'selected':''}>${rankName(r.id)}</option>`).join('')}</select></label><p>最高、创始、白羽同级。级别不授予账号发放权。</p><details><summary>各级操作范围</summary>${ranks.map(r=>`<p>${rankName(r.id)}：${r.write.map(k=>({world:'世界概览',entries:'设定词条',timeline:'时间线',state:'关系图与待办',archive:'来源档案'}[k])).join('、')||'只读'}</p>`).join('')}</details><button class="primary">创建账号</button></form><h3>已发放账号</h3>${rows.map(a=>`<p>${esc(a.username)} · ${esc(rankName(a.rank))} · ${a.active?'启用':'停用'} ${a.role!=='owner'?`<select data-rank-for="${esc(a.id)}">${ranks.map(r=>`<option value="${r.id}" ${a.rank===r.id?'selected':''}>${rankName(r.id)}</option>`).join('')}</select><button data-set-rank="${esc(a.id)}">设置级别</button><button data-account="${esc(a.id)}" data-active="${a.active?'false':'true'}">${a.active?'停用':'启用'}</button><input type="password" data-reset-password="${esc(a.id)}" placeholder="新密码" autocomplete="new-password"><button data-reset="${esc(a.id)}">重置密码</button>`:''}</p>`).join('')}`:''}<details><summary>修改我的密码</summary><form id="own-password"><label>当前密码<input type="password" name="old" required></label><label>新密码<input type="password" name="password" required></label><button>保存并重新登录</button></form></details><p id="account-message" role="status"></p>`;if(!d.open)d.showModal();}catch(e){alert(e.message);}}
 button.onclick=open;d.addEventListener('click',async e=>{if(e.target.id==='account-close')d.close();const b=e.target.closest('[data-account],[data-reset],[data-set-rank]');if(!b)return;try{if(b.dataset.setRank){await window.kuatCloud.updateAccount(b.dataset.setRank,undefined,undefined,d.querySelector('[data-rank-for="'+b.dataset.setRank+'"]').value);}else if(b.dataset.reset){const pass=d.querySelector('[data-reset-password="'+b.dataset.reset+'"]').value;if(!pass)return;await window.kuatCloud.updateAccount(b.dataset.reset,undefined,pass);}else await window.kuatCloud.updateAccount(b.dataset.account,b.dataset.active==='true');await open();}catch(error){d.querySelector('#account-message').textContent=error.message;}});
 d.addEventListener('submit',async e=>{e.preventDefault();const f=e.target;const b=f.querySelector('button');b.disabled=true;try{if(f.id==='issue-account'){await window.kuatCloud.issue(f.elements.username.value,f.elements.password.value,f.elements.role.value);await open();d.querySelector('#account-message').textContent='账号已创建，请由你将账号和初始密码交给使用者。';}else{await CloudState.flush();await window.kuatCloud.password(f.elements.old.value,f.elements.password.value);location.reload();}}catch(error){d.querySelector('#account-message').textContent=error.message;}finally{b.disabled=false;}});
}
