/* Fictional terminal presentation. Real authorization remains server controlled. */
window.KuatTerminal=(()=>{
 const auth=document.createElement('dialog');auth.className='terminal-auth';
 auth.innerHTML=`<div class="terminal-caption">K.U.A.T / UNIFIED TERMINAL <span>IDENTITY GATEWAY</span></div><div class="auth-center"><div class="auth-orbit"><img src="assets/kuat-brand-ring.svg" alt="K.U.A.T"></div><p class="terminal-eyebrow">KNOWLEDGE · UNDERSTANDING · APPLICATION · TRANSFORM</p><h1>身份认证通过</h1><p class="auth-description">正在展开你的开发工作区</p><div class="auth-clearance"><span>权限认证：</span><strong><span class="rank-symbol">Ω</span><span class="rank-name">Omega</span></strong><small>PROJECT WORLD · 开发接入</small></div><div class="auth-track"><i></i></div><p class="auth-footnote">终端权限开放中</p></div><footer>K.U.A.T Administration <span>AUTHORIZED DEVELOPMENT ACCESS</span></footer>`;
 document.body.append(auth);auth.addEventListener('cancel',e=>e.preventDefault());
 function identity(){const access=window.KuatAccess;const rank=access?.ranks?.find(r=>r.id===access.rank);const aliases={Infinite:'Infinite',Orange:'Origin',White:'Shiro',Purple:'K.U.A.T',Darkblue:'Cabinet',Red:'Alpha',Blue:'Beta',Cyan:'Tech',Green:'Gamma',Grey:'Omega'};const symbols={Infinite:'∞',White:'Λ',Red:'Α',Blue:'Β',Green:'Γ',Grey:'Ω'};return {name:aliases[rank?.id]||rank?.alias||'未知',symbol:symbols[rank?.id]||'◇'};}
 function welcome(){const rank=identity();auth.querySelector('.rank-name').textContent=rank.name;auth.querySelector('.rank-symbol').textContent=rank.symbol;return new Promise(resolve=>{auth.classList.remove('auth-exit');auth.showModal();let closing=false;const close=()=>{if(closing)return;closing=true;clearTimeout(timer);auth.classList.add('auth-exit');setTimeout(()=>{auth.close();auth.classList.remove('auth-exit');resolve();},650);};const timer=setTimeout(close,matchMedia('(prefers-reduced-motion: reduce)').matches?200:6400);});}
 const modules=[['01','Project World','世界构建与设定开发','open'],['02','行政中枢','K.U.A.T Administration'],['03','产业统筹','集团协同与资源调度'],['04','工作发布','任务发布与执行调度'],['05','科研网络','研究项目与技术档案'],['06','星区事务','辖区协调与文明事务']];
 function install(){
  const rank=identity();
  const button=document.createElement('button');button.className='terminal-launch';button.innerHTML='<span>◈ 总平台</span><small>OMEGA / 开发接入 <b>↗</b></small>';
  button.querySelector('small').firstChild.textContent=rank.name+' / 开发接入 ';document.querySelector('.workspace').after(button);
  const portal=document.createElement('dialog');portal.className='terminal-portal';portal.innerHTML=`<header><div><p class="terminal-eyebrow">K.U.A.T / UNIFIED TERMINAL</p><h2>系统总览</h2></div><button class="terminal-close" aria-label="关闭总平台">✕</button></header><div class="terminal-summary"><div><span class="terminal-chip">Ω OMEGA</span><h3>开发接入区</h3><p>当前终端开放 Project World 创作模块。</p></div><img src="assets/kuat-brand-ring.svg" alt=""></div><div class="terminal-modules">${modules.map(([id,title,desc,open])=>`<button class="terminal-module ${open?'is-open':''}" data-module="${id}" ${open?'':'aria-disabled="true"'}><small>${id} / ${open?'AVAILABLE':'RESTRICTED'}</small><h3>${title}</h3><p>${desc}</p><span>${open?'进入创作工作区 ↗':'未开放 · ⌑'}</span></button>`).join('')}</div><p class="terminal-notice" role="status">未开放模块为世界观展示入口，暂不提供实际功能。</p><footer>KNOWLEDGE / UNDERSTANDING / APPLICATION / TRANSFORM</footer>`;portal.querySelector('.terminal-chip').textContent=rank.symbol+' '+rank.name;document.body.append(portal);
  button.onclick=()=>portal.showModal();portal.querySelector('.terminal-close').onclick=()=>portal.close();portal.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>{if(b.dataset.module==='01')portal.close();else portal.querySelector('.terminal-notice').textContent=b.querySelector('h3').textContent+'未向本终端开放。此入口仅作世界观展示。';});
 }
 return {welcome,install};
})();

