const TimelineView=(()=>{
 let data=structuredClone(TimelineModel.initial),ready=false,failed=false,busy=false,selected=null,query='',track='全部',zoom=1,refresh,toast,view=null;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const enabled=()=>ready&&!failed&&!busy;
 const time=e=>e.dateLabel||(e.start===null?'时间待定':`${e.start}${e.end!==null&&e.end!==e.start?' — '+e.end:''} ${data.unit}`);
 const priority=e=>`${e.importance??'普通'}事件 · ${['一','二','三','四','五'][(e.level??3)-1]}级`;
 const entries=()=>EntriesView.snapshot().entries;
 async function persist(next){if(!enabled())return false;busy=true;try{TimelineModel.validate(next);if(window.kuat?.saveTimeline)data=await window.kuat.saveTimeline(next,data.storeRevision);else{const old=JSON.parse(CloudState.getItem('kuat-timeline-v1')||'null');if((old?.storeRevision||0)!==data.storeRevision)throw Error('其他窗口已修改时间线，请重新打开');const saved={...next,storeRevision:data.storeRevision+1};CloudState.setItem('kuat-timeline-v1',JSON.stringify(saved));data=saved;}return true;}catch(e){toast('保存失败：'+e.message);return false;}finally{busy=false;}}
 function detail(e){if(!e)return '<div class="tl-empty"><span>◷</span><h3>选择一个事件</h3><p>查看正文、关联设定与时间信息。</p></div>';const source=entries().find(x=>x.id===e.entryId);return `<div class="tl-detail-heading"><small>${esc(e.track)} · ${priority(e)}</small><h2>${esc(e.title)}</h2><p>${esc(data.calendar)} · ${esc(time(e))}</p></div><div class="tl-detail-actions"><button data-tl-edit="${esc(e.id)}">编辑事件</button><button data-tl-remove="${esc(e.id)}">移除</button></div>${e.entryId?`<p class="tl-source">引用设定：${esc(source?.title||'词条暂不可用')} ${source?`<button data-tl-source="${esc(source.id)}">查看设定</button>`:''}</p>`:''}<div class="archive-prose">${ArchiveView.markdown(e.body||'暂无事件说明')}</div>`;}
 function render(){const all=TimelineModel.ordered(data.events);const shown=all.filter(e=>(track==='全部'||e.track===track)&&[e.title,e.body,e.track,e.dateLabel].join('\n').toLowerCase().includes(query.toLowerCase()));const dated=shown.filter(e=>e.start!==null),undated=shown.filter(e=>e.start===null);const bounds=TimelineModel.extent(dated),width=1000*zoom,pos=n=>(80+(n-bounds.min)/(bounds.max-bounds.min)*740)*zoom;const tracks=[...new Set(all.map(e=>e.track))];const sel=data.events.find(e=>e.id===selected);
 return `<section class="page-heading"><div><h1>时间线</h1><p>${esc(data.calendar)} · ${esc(data.unit)} / ${data.events.length} 个事件 ${data.pendingSync?'· 待同步':''}</p></div><div class="tl-actions"><button id="tl-settings" ${enabled()?'':'disabled'}>历法设置</button><button id="tl-export">导出时间线</button><button class="primary" id="tl-new" ${enabled()?'':'disabled'}>＋ 添加事件</button></div></section>${failed?'<p role="alert">时间线读取失败，原数据未覆盖。请重开程序后重试。</p>':!ready?'<p>正在读取时间线…</p>':''}<div class="tl-toolbar"><input id="tl-search" placeholder="搜索事件、正文或时间标记…" aria-label="搜索时间线" value="${esc(query)}"><select id="tl-track" aria-label="筛选轨道"><option>全部</option>${tracks.map(t=>`<option ${track===t?'selected':''}>${esc(t)}</option>`).join('')}</select><div><button id="tl-out" aria-label="缩小">−</button><span>${Math.round(zoom*100)}%</span><button id="tl-in" aria-label="放大">＋</button><button id="tl-fit">适应</button></div></div><div class="tl-layout"><section class="tl-board"><div class="tl-scroll" tabindex="0" aria-label="事件时间轴，可无限左右平移"><div class="tl-axis-content" data-width="${width}"><div class="tl-ruler">${Array.from({length:11},(_,i)=>{const n=bounds.min+(bounds.max-bounds.min)*i/10;return `<span data-left="${pos(n)}">${Number(n.toFixed(3))}</span>`;}).join('')}</div>${dated.map((e,i)=>`<button class="tl-event ${e.end===null?'instant':'interval'} ${i%2?'below':'above'} ${selected===e.id?'selected':''}" data-tl-select="${esc(e.id)}" data-left="${pos(e.start)}" data-color="${e.color}" data-width="${Math.max(14,pos(e.end??e.start)-pos(e.start))}"><span class="tl-event-bar"></span><span class="tl-stem"></span><span class="tl-event-title">${esc(e.title)}<small>${esc(time(e))} · ${esc(e.track)} · ${priority(e)}</small></span></button>`).join('')||'<div class="tl-axis-empty">添加事件，沿时间轴展开世界的历程</div>'}</div></div><section class="tl-undated"><h3>待定时间 <small>${undated.length}</small></h3><div>${undated.map(e=>`<button class="${selected===e.id?'selected':''}" data-tl-select="${esc(e.id)}"><i data-color="${e.color}"></i>${esc(e.title)}<small>${esc(e.track)}</small></button>`).join('')||'<p>没有待定事件</p>'}</div></section><p id="tl-density" class="tl-hint" role="status"></p><p class="tl-hint">拖动空白处左右移动，Ctrl＋滚轮缩放，Shift＋滚轮横向移动。事件交错排列于主轴两侧；留空坐标的事件保留在待定区。</p></section><aside class="tl-detail">${detail(sel)}</aside></div>`;
 }
 function redraw(){const scroll=document.querySelector('.tl-scroll');const x=scroll?.scrollLeft||0,y=scroll?.scrollTop||0;refresh();const next=document.querySelector('.tl-scroll');if(next){next.scrollLeft=x;next.scrollTop=y;}}
 function changeZoom(value,anchor){const el=document.querySelector('.tl-scroll');if(!el||!view)return;const x=(anchor??el.clientWidth/2)-el.clientWidth/2,oldScale=Number(el.dataset.scale);zoom=Math.max(.01,Math.min(1000,value));const newScale=el.clientWidth*.74*zoom/view.span;view.center+=x/oldScale-x/newScale;redraw();}
 function editor(id){if(!enabled())return;const e=data.events.find(x=>x.id===id)||{id:crypto.randomUUID(),title:'',track:'主线',start:null,end:null,dateLabel:'',entryId:'',body:'',color:'#6477bd'};const d=document.querySelector('#tl-editor');d.innerHTML=`<form id="tl-form" data-id="${esc(e.id)}"><div class="dialog-head"><h2>${id?'编辑事件':'添加事件'}</h2><button type="button" data-tl-close>✕</button></div><label>引用事件词条（可选，选择后复制标题与正文，后续分别编辑）<select name="entryId"><option value="">独立事件</option>${entries().filter(x=>x.type==='事件'||x.id===e.entryId).map(x=>`<option value="${esc(x.id)}" ${e.entryId===x.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label><div class="entry-form-grid"><label>事件名称<input name="title" required maxlength="120" value="${esc(e.title)}"></label><label>轨道<input name="track" required maxlength="60" value="${esc(e.track)}" list="tl-tracks"><datalist id="tl-tracks">${[...new Set(data.events.map(x=>x.track))].map(t=>`<option value="${esc(t)}"></option>`).join('')}</datalist></label><label>重要程度<select name="importance">${['核心','重要','普通'].map(v=>`<option value="${v}" ${(e.importance??'普通')===v?'selected':''}>${v}事件</option>`).join('')}</select></label><label>级别（一级最高）<select name="level">${[1,2,3,4,5].map(v=>`<option value="${v}" ${(e.level??3)===v?'selected':''}>${['一','二','三','四','五'][v-1]}级</option>`).join('')}</select></label><label>事件类型<select name="timeMode"><option value="instant" ${e.end===null?'selected':''}>瞬时事件 · 时间点</option><option value="interval" ${e.end!==null?'selected':''}>区间事件 · 时间段</option></select></label><label><span id="tl-start-label">${e.end===null?'发生时间':'开始时间'}（留空为待定）</span><input type="number" step="any" min="-1000000000" max="1000000000" name="start" value="${e.start??''}"></label><label id="tl-end-field" ${e.end===null?'hidden':''}>结束时间<input ${e.end===null?'disabled':'required'} type="number" step="any" min="-1000000000" max="1000000000" name="end" value="${e.end??''}"></label><label>时间标记<input name="dateLabel" maxlength="120" placeholder="例如：某历元年·春" value="${esc(e.dateLabel)}"></label><label>颜色<input type="color" name="color" value="${e.color}"></label></div><div class="entry-markdown-workspace"><label>事件说明 · Markdown<textarea name="body" rows="10" maxlength="200000">${esc(e.body)}</textarea></label><section class="entry-preview-pane"><h3>实时预览</h3><div id="tl-preview" class="archive-prose">${ArchiveView.markdown(e.body)}</div></section></div><p id="tl-error" role="alert"></p><div class="dialog-footer"><span>保存到云端 · 标记待同步</span><button class="primary" id="tl-save">保存事件</button></div></form>`;d.showModal();}
 function settings(){if(!enabled())return;const d=document.querySelector('#tl-settings-dialog');d.innerHTML=`<form id="tl-settings-form"><h2>历法设置</h2><p>时间坐标使用统一单位，不换算现实日期。</p><label>历法名称<input name="calendar" required maxlength="60" value="${esc(data.calendar)}"></label><label>坐标单位<input name="unit" required maxlength="60" value="${esc(data.unit)}"></label><p>修改名称或单位不会换算已有坐标。</p><div class="dialog-footer"><button type="button" data-tl-close>取消</button><button class="primary">保存</button></div></form>`;d.showModal();}
 function install(renderPage,notify){refresh=renderPage;toast=notify;for(const id of ['tl-editor','tl-settings-dialog','tl-source-dialog']){const d=document.createElement('dialog');d.id=id;document.body.append(d);d.addEventListener('click',e=>{if(e.target.closest('[data-tl-close]'))d.close();});}
 document.querySelector('#main').addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.tlSelect){selected=b.dataset.tlSelect;redraw();}if(b.dataset.tlEdit)editor(b.dataset.tlEdit);if(b.id==='tl-new')editor();if(b.id==='tl-settings')settings();if(['tl-in','tl-out','tl-fit'].includes(b.id)){if(b.id==='tl-fit'){view=null;zoom=1;redraw();}else changeZoom(zoom*(b.id==='tl-in'?1.4:1/1.4));}if(b.dataset.tlRemove&&enabled()&&confirm('从时间线移除此事件？引用的设定词条不会删除。')){if(await persist({...data,events:data.events.filter(e=>e.id!==b.dataset.tlRemove),pendingSync:true,updatedAt:new Date().toISOString()})){selected=null;redraw();}}if(b.dataset.tlSource){const e=entries().find(e=>e.id===b.dataset.tlSource);if(e){const d=document.querySelector('#tl-source-dialog');d.innerHTML=`<div class="dialog-head"><h2>${esc(e.title)}</h2><button data-tl-close>关闭</button></div><div class="archive-prose">${ArchiveView.markdown(e.body)}</div>`;d.showModal();}}if(b.id==='tl-export'){if(!ready||failed)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Project-World-时间线.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('时间线已导出，尚未同步到 Matrees');}});
 let panDrag=null;
 const stopPan=()=>{if(!panDrag)return;const {el,id}=panDrag;panDrag=null;el.classList.remove('tl-panning');if(el.hasPointerCapture(id))el.releasePointerCapture(id);};
 document.querySelector('#main').addEventListener('pointerdown',e=>{const el=e.target.closest('.tl-scroll');if(!el||e.button!==0||e.target.closest('button,input,select,textarea,a'))return;const rect=el.getBoundingClientRect();if(e.clientY>=rect.top+el.clientHeight||e.clientX>=rect.left+el.clientWidth)return;e.preventDefault();stopPan();panDrag={el,id:e.pointerId,x:e.clientX,center:view.center,scale:Number(el.dataset.scale)};el.setPointerCapture(e.pointerId);el.classList.add('tl-panning');});
 document.querySelector('#main').addEventListener('pointermove',e=>{if(!panDrag||e.pointerId!==panDrag.id)return;e.preventDefault();view.center=panDrag.center+(panDrag.x-e.clientX)/panDrag.scale;afterRender();});
 for(const type of ['pointerup','pointercancel','lostpointercapture'])document.querySelector('#main').addEventListener(type,e=>{if(panDrag?.id===e.pointerId)stopPan();});
 window.addEventListener('blur',stopPan);
 document.querySelector('#main').addEventListener('wheel',e=>{const el=e.target.closest('.tl-scroll');if(!el)return;if(e.ctrlKey){e.preventDefault();changeZoom(zoom*Math.exp(-e.deltaY*.002),e.clientX-el.getBoundingClientRect().left);}else if(e.shiftKey||e.deltaX){e.preventDefault();view.center+=(e.shiftKey?(e.deltaY||e.deltaX):e.deltaX)/Number(el.dataset.scale);afterRender();}},{passive:false});
 window.addEventListener('resize',()=>{if(document.querySelector('.tl-scroll'))afterRender();});
 document.querySelector('#main').addEventListener('input',e=>{if(e.target.id==='tl-search'){const caret=e.target.selectionStart;query=e.target.value;redraw();const input=document.querySelector('#tl-search');input.focus();input.setSelectionRange(caret,caret);}});
 document.querySelector('#main').addEventListener('change',e=>{if(e.target.id==='tl-track'){track=e.target.value;redraw();}});
 const d=document.querySelector('#tl-editor');d.addEventListener('input',e=>{if(e.target.name==='body')document.querySelector('#tl-preview').innerHTML=ArchiveView.markdown(e.target.value);});d.addEventListener('change',e=>{if(e.target.name==='timeMode'){const f=document.querySelector('#tl-form'),interval=e.target.value==='interval';document.querySelector('#tl-end-field').hidden=!interval;f.elements.end.disabled=!interval;f.elements.end.required=interval;f.elements.start.required=interval;document.querySelector('#tl-start-label').textContent=interval?'开始时间':'发生时间（留空为待定）';}if(e.target.name==='entryId'){const entry=entries().find(x=>x.id===e.target.value);if(entry){const f=document.querySelector('#tl-form');f.elements.title.value=entry.title;f.elements.body.value=entry.body;document.querySelector('#tl-preview').innerHTML=ArchiveView.markdown(entry.body);}}});
 d.addEventListener('submit',async ev=>{ev.preventDefault();if(!enabled())return;const f=ev.target;try{const e=Object.fromEntries(new FormData(f));e.id=f.dataset.id;e.title=e.title.trim();e.track=e.track.trim();e.start=e.start===''?null:Number(e.start);if(e.timeMode==='interval'&&(e.start===null||!e.end))throw Error('区间事件需要填写开始和结束时间');e.end=e.timeMode==='instant'?null:Number(e.end);delete e.timeMode;e.level=Number(e.level);const next=TimelineModel.update(data,e);f.querySelector('#tl-save').disabled=true;if(await persist(next)){selected=e.id;d.close();redraw();toast('事件已保存');}}catch(e){document.querySelector('#tl-error').textContent=e.message;}finally{f.querySelector('#tl-save').disabled=false;}});
 document.querySelector('#tl-settings-dialog').addEventListener('submit',async ev=>{ev.preventDefault();if(!enabled())return;const fields=Object.fromEntries(new FormData(ev.target));fields.calendar=fields.calendar.trim();fields.unit=fields.unit.trim();if(await persist({...data,...fields,pendingSync:true,updatedAt:new Date().toISOString()})){ev.target.closest('dialog').close();redraw();}});
 (async()=>{try{const saved=window.kuat?.loadTimeline?await window.kuat.loadTimeline():JSON.parse(CloudState.getItem('kuat-timeline-v1')||'null');if(saved)data=TimelineModel.validate(saved);}catch{failed=true;}finally{ready=true;refresh();}})();
 }
 function afterRender(){const scroll=document.querySelector('.tl-scroll');if(!scroll)return;const width=scroll.clientWidth;const nodes=[...document.querySelectorAll('.tl-event')],ids=new Set(nodes.map(e=>e.dataset.tlSelect)),events=data.events.filter(e=>ids.has(e.id));
 if(!view){const bounds=TimelineModel.extent(events);view={center:(bounds.min+bounds.max)/2,span:bounds.max-bounds.min};}
 const scale=width*.74*zoom/view.span,pos=n=>width/2+(n-view.center)*scale;scroll.dataset.center=view.center;scroll.dataset.scale=scale;
 const canvas=document.querySelector('.tl-axis-content');canvas.style.width='100%';canvas.style.height='460px';canvas.style.setProperty('--axis-y','230px');
 const raw=90/scale,power=10**Math.floor(Math.log10(raw)),step=([1,2,5,10].find(n=>n*power>=raw)||10)*power;const left=view.center-width/2/scale,right=view.center+width/2/scale,ticks=[];
 for(let i=0,n=Math.ceil(left/step)*step;i<100&&n<=right;i++,n+=step){ticks.push(`<span data-tick="${n}">${Number(n.toPrecision(10))}</span>`);}
 const ruler=document.querySelector('.tl-ruler');ruler.innerHTML=ticks.join('');ruler.querySelectorAll('span').forEach(e=>e.style.left=pos(Number(e.dataset.tick))+'px');
 const inView=events.filter(e=>pos(e.end??e.start)>=-200&&pos(e.start)<=width);const positions=new Map(inView.map(e=>[e.id,Math.max(0,pos(e.start))]));const visible=TimelineModel.visibleAtScale(inView,e=>positions.get(e.id));const set=new Set(visible);
 nodes.forEach(el=>{const e=events.find(x=>x.id===el.dataset.tlSelect);el.hidden=!set.has(e.id);const i=visible.indexOf(e.id);el.classList.toggle('above',i%2===0);el.classList.toggle('below',i%2===1);el.style.setProperty('--offset','60px');el.style.setProperty('--event-color',e.color);el.style.left=Math.max(0,pos(e.start))+'px';el.style.width=Math.max(14,Math.min(width,pos(e.end??e.start))-Math.max(0,pos(e.start)))+'px';});
 document.querySelectorAll('.tl-undated [data-color]').forEach(e=>e.style.backgroundColor=e.dataset.color);
 const count=inView.length-visible.length;document.querySelector('#tl-density').textContent=count?`当前尺度隐藏 ${count} 个事件${visible.length?'，放大可逐步显示。':'，仅显示时间轴；放大可恢复事件。'}`:`当前视窗显示 ${visible.length} 个事件 · 时间轴可向左右无限延伸`;
 }
 return {render,install,afterRender,summary:()=>ready&&!failed?`${data.calendar} · ${data.events.length} 个事件`:'时间线'};
})();
