const modules=[['home','⌂','首页'],['works','▣','作品'],['proposals','✦','提案中心'],['overview','◈','世界概览'],['cards','▤','设定卡片'],['timeline','◷','时间线'],['simulation','⌬','世界模拟'],['map','⌖','世界地图'],['relations','⌘','关系图'],['gallery','▧','插图集'],['archive','▥','来源档案']];
let tasks=[];try{const saved=JSON.parse(CloudState.getItem('kuat-tasks-v1')||'[]');if(Array.isArray(saved)&&saved.every(t=>typeof t.text==='string'&&typeof t.done==='boolean'))tasks=saved;}catch{}
let world=structuredClone(WorldModel.initial), active='home';
const $=s=>document.querySelector(s); const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function render(){
 document.body.classList.toggle('relations-view',active==='relations');
 document.body.classList.toggle('home-view',active==='home');
 document.body.classList.toggle('archive-view',['cards','archive','relations','timeline','simulation'].includes(active));
 document.body.classList.toggle('collection-view',['works','proposals'].includes(active));
 document.body.classList.toggle('works-view',active==='works');
 document.body.classList.toggle('proposals-view',active==='proposals');
 document.body.classList.toggle('settings-view',active==='cards');
 $('#navigation').innerHTML=modules.map(([id,icon,label])=>`<button data-page="${id}" class="nav-item ${id===active?'active':''}"><span>${icon}</span>${label}${id===active?'<i></i>':''}</button>`).join('')+'<p class="nav-label future-label">未来工作区</p><div class="disabled-nav">♧ <span>共创</span><small>暂缓</small></div>';
 $('#crumb').textContent=modules.find(x=>x[0]===active)[2];const canEditOverview=Boolean(window.KuatAccess?.write?.includes('world'));$('#edit').hidden=active!=='overview'||!canEditOverview;
 $('#main').innerHTML=active==='home'?home():active==='works'?worksWorkspace():active==='proposals'?proposalCenter():active==='overview'?overview():active==='cards'?EntriesView.render():active==='archive'?ArchiveView.render():active==='relations'?RelationsView.render():active==='timeline'?TimelineView.render():active==='simulation'?SimulationView.render():placeholder();
 if(active==='timeline')TimelineView.afterRender();
 $('#outline').innerHTML=active==='overview'?'<a href="#background" class="outline-link">01 <span>世界背景</span></a><a href="#calendar" class="outline-link">02 <span>世界历法</span></a><a href="#concept" class="outline-link">03 <span>世界概念</span></a>':active==='simulation'?'<a href="#sim-setup-form" class="outline-link">01 <span>模拟设定</span></a><a href="#sim-actor-search" class="outline-link">02 <span>参与设定</span></a><a href="#sim-record-form" class="outline-link">03 <span>模拟记录</span></a>':'<p class="muted">模块建设中</p>';
 $('#activities').innerHTML=world.changes.length?world.changes.slice(0,5).map(c=>`<div class="activity"><i></i><div>${escape(c.text)}<small>白羽奈绪 · ${date(c.at)}</small></div></div>`).join(''):'<div class="empty-activity">还没有编辑记录<br><small>保存一次概览，记录便从这里开始。</small></div>';
 $('#sync-status').textContent=world.pendingSync?'● 有待同步的设定更新':'同步通道尚未接入';
 $('#save-state').textContent=world.updatedAt?'已保存 · '+date(world.updatedAt):'云端档案';
}
function activityList(){return world.changes.length?world.changes.slice(0,4).map(c=>`<button class="recent-row" data-go="overview"><span class="tile-icon">▤</span><span><strong>${escape(c.text)}</strong><small>${date(c.at)}</small></span><b>›</b></button>`).join(''):'<div class="empty-state">暂无变更记录<small>编辑并保存世界概览后，记录会显示在这里。</small></div>';}
function home(){const descriptions={overview:'查看背景与基础概念',cards:'编辑、查询与连接设定',timeline:'梳理事件与时代',simulation:'设置前提并记录世界推演',map:'管理空间与地点',relations:'连接人物与设定',gallery:'整理视觉参考',archive:'阅读原始资料'};const contentModules=modules.filter(([id])=>!['home','works','proposals'].includes(id));return `<div class="home-heading"><h1>首页</h1><p>${new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'})}</p></div><div class="home-grid"><div class="home-primary"><section class="home-banner"><div><h2>${escape(world.name)}</h2><p>世界构建项目</p><div class="banner-tags"><span>♧ 私有项目</span><span>● 构建中</span></div><button class="primary" data-go="overview">打开世界概览 →</button></div></section><section class="home-panel"><h2>继续工作</h2><button class="recent-row" data-go="overview"><span class="tile-icon">▤</span><span><strong>世界背景 · 概览</strong><small>${world.updatedAt?'修改于 '+date(world.updatedAt):'打开概览，开始整理世界设定'}</small></span><b>›</b></button></section><section class="home-panel"><h2>世界内容</h2><div class="content-grid">${contentModules.map(([id,icon,label])=>`<button class="content-tile" data-go="${id}"><span class="tile-icon">${icon}</span><span><strong>${label}</strong><small>${descriptions[id]}</small>${id==='cards'?'<em>'+IDEAArchive.documents.length+' 份已归档</em>':!['overview','relations','timeline','simulation'].includes(id)?'<em>待开发</em>':''}</span><b>›</b></button>`).join('')}</div></section></div><div class="home-secondary"><section class="home-panel"><div class="home-panel-heading"><h2>当前事项</h2><button class="quiet" id="add-task" aria-label="添加事项">＋</button></div><div id="task-list">${tasks.length?tasks.map((t,i)=>`<label class="task-row"><input type="checkbox" data-task="${i}" ${t.done?'checked':''}><span class="${t.done?'done':''}">${escape(t.text)}</span></label>`).join(''):'<div class="empty-state">还没有待办事项<small>点击右上角 ＋ 添加需要跟进的内容。</small></div>'}</div><form id="task-form" hidden><input id="task-input" aria-label="事项内容" placeholder="输入事项，按回车添加" maxlength="120" required><button class="primary" type="submit">添加</button></form></section><section class="home-panel"><h2>最近变更</h2>${activityList()}</section><section class="home-panel home-sync"><h2>Matrees 状态</h2><div class="sync-summary"><span class="tile-icon">☁</span><div><strong>未接入同步</strong><p>${world.pendingSync?'有云端设定更新等待同步。':'当前为云端工作区。'}</p></div></div><button data-sync>导出待同步内容</button><small>导出不会自动更新 Matrees</small></section></div></div><footer class="canvas-footer"><span>云端工作区 / Project World</span><span>K.U.A.T · 0.1.0</span></footer>`;}
function overview(){return `<section class="page-heading"><div><h1>世界概览</h1><p>背景档案与核心设定</p></div><span class="outline-badge">私有文档</span></section><section class="panel" id="background"><div class="panel-title"><h2>世界背景</h2><button class="text-button" data-edit>编辑</button></div><h2 class="document-title">${escape(world.name)}</h2><p class="document-subtitle">${escape(world.subtitle)}</p><p class="prose">${escape(world.background)}</p><div class="hero-tags">${world.tags.map(t=>`<span>${escape(t)}</span>`).join('')}</div></section><section class="panel" id="calendar"><div class="panel-title"><h2>世界历法</h2><button class="text-button" data-go="timeline">打开时间线 ↗</button></div><div class="calendar-empty"><span class="calendar-symbol">◷</span><div><h3>${escape(TimelineView.summary())}</h3><p>在时间线中设置历法、添加事件并安排时间。</p></div></div></section><section class="panel" id="concept"><div class="panel-title"><h2>世界概念</h2></div><div class="concept-content"><span class="concept-icon">✧</span><p class="prose">${escape(world.concept)}</p></div></section>`;}
function worksWorkspace(){return `<section class="collection-page works-page"><div class="collection-toolbar"><div class="collection-toolbar-left"><button class="collection-select" type="button">全部类型 <span>⌄</span></button><label class="collection-search"><span>⌕</span><input aria-label="搜索作品名称" placeholder="搜索作品名称"></label></div><div class="collection-toolbar-right"><button class="collection-refresh quiet" type="button" aria-label="刷新作品">↻</button><button class="collection-create quiet" type="button" data-works-create>⌘&nbsp; 新建作品</button></div></div><div class="collection-empty"><div class="collection-empty-icon">▣</div><h1>还没有公开作品</h1><p>公开作品将在这里展示</p><button class="collection-empty-action primary" type="button" data-works-create>⌘&nbsp; 新建作品</button></div></section>`;}
function proposalFilterGroup(title,items){return `<section class="proposal-filter-group"><h3>${title}</h3><div class="proposal-filter-chips">${items.map((item,index)=>`<button type="button" class="proposal-filter-chip ${index===0?'active':''}" data-proposal-filter>${item}<b>0</b></button>`).join('')}</div></section>`;}
function proposalCenter(){return `<section class="collection-page proposal-page"><header class="proposal-page-head"><div class="proposal-page-title"><span>⌁</span><strong>提案中心</strong></div><div class="proposal-page-actions"><button class="quiet" type="button" data-proposal-refresh aria-label="刷新提案">↻</button><button class="quiet" type="button" aria-label="切换视图">▣</button></div></header><div class="proposal-layout"><aside class="proposal-filters">${proposalFilterGroup('审核状态',['全部','待审核','已通过','已拒绝'])}${proposalFilterGroup('提案类型',['全部类型','概念提案','事件提案','设定提案','关联关系提案','作品提案','小说章节提案','地图提案','地图坐标提案','故事提案','场次提案','剧本集提案'])}${proposalFilterGroup('操作类型',['全部操作','创建','更新','删除','发布'])}</aside><section class="proposal-results"><div class="proposal-empty"><div class="proposal-empty-icon">⌘</div><h1>暂无提案</h1><p>当前没有需要审核的提案</p></div></section></div></section>`;}
function placeholder(){const m=modules.find(x=>x[0]===active);return `<section class="page-heading"><div><div class="section-kicker">PROJECT WORLD WORKSPACE</div><h1>${m[2]}</h1><p>世界创作工作台的一部分。</p></div></section><div class="module-empty"><span>${m[1]}</span><h2>${m[2]}，即将开始构建</h2><p>当前版本先实现世界概览。这个模块已预留位置，尚未提供编辑功能。</p><button class="primary" data-go="overview">返回世界概览</button></div>`;}
$('#navigation').onclick=e=>{const b=e.target.closest('[data-page]');if(b){active=b.dataset.page;render();window.scrollTo(0,0);}};
$('#main').onclick=e=>{const b=e.target.closest('[data-go]');if(b){active=b.dataset.go;render();window.scrollTo(0,0);}if(e.target.closest('[data-edit]'))$('#edit').click();if(e.target.closest('[data-sync]'))download(true);if(e.target.closest('#add-task')){$('#task-form').hidden=false;$('#task-input').focus();}if(e.target.closest('[data-works-create]'))toast('作品创建入口已预留，作品数据模块接入后即可创建。');if(e.target.closest('[data-proposal-refresh]'))render();const filter=e.target.closest('[data-proposal-filter]');if(filter){filter.closest('.proposal-filter-chips').querySelectorAll('.proposal-filter-chip').forEach(button=>button.classList.remove('active'));filter.classList.add('active');}};
$('#main').addEventListener('submit',e=>{if(e.target.id!=='task-form')return;e.preventDefault();const text=$('#task-input').value.trim();if(!text)return;const next=[...tasks,{text,done:false}];try{CloudState.setItem('kuat-tasks-v1',JSON.stringify(next));tasks=next;render();}catch{toast('事项保存失败，请检查云端连接');}});
$('#main').addEventListener('change',e=>{if(!e.target.matches('[data-task]'))return;const next=tasks.map((t,i)=>i===Number(e.target.dataset.task)?{...t,done:e.target.checked}:t);try{CloudState.setItem('kuat-tasks-v1',JSON.stringify(next));tasks=next;render();}catch{e.target.checked=!e.target.checked;toast('事项保存失败');}});
$('.brand').onclick=e=>{e.preventDefault();active='home';render();};
$('#edit').onclick=()=>{const f=$('#edit-form');for(const k of ['name','subtitle','background','concept'])f.elements[k].value=world[k];f.elements.tags.value=world.tags.join('，');$('#editor').showModal();};
$('#close').onclick=()=>$('#editor').close();
$('#edit-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const fields=Object.fromEntries(f);fields.tags=fields.tags.split(/[,，]/).map(x=>x.trim()).filter(Boolean);const next=WorldModel.update(world,fields);try{if(window.kuat)await window.kuat.save(next);else CloudState.setItem('kuat-world-v1',JSON.stringify(next));world=next;$('#editor').close();render();toast('概览已保存，更新已标记为待同步');}catch{toast('云端保存失败，请检查连接后重试');}};
function download(sync=false){const data=sync?{type:'matrees-manual-sync',exportedAt:new Date().toISOString(),target:'https://matrees.cn/world/overview?worldId=1922648981268111360',status:'pending',world}:world;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=sync?'Project-World-待同步.json':'Project-World-档案.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(sync?'已导出待同步内容，尚未更新 Matrees':'世界概览已导出（不含设定资料库）');}
$('#export').onclick=()=>download();$('#sync-export').onclick=()=>download(true);
(async()=>{try{const saved=window.kuat?await window.kuat.load():JSON.parse(CloudState.getItem('kuat-world-v1')||'null');if(saved)world=WorldModel.validate(saved);}catch{toast('现有档案无法读取，显示初始内容；原数据未自动覆盖');}$('#storage-kind').textContent=window.kuat?'数据保存在云端档案':'数据保存在云端';render();})();
// Stop decorative animation while the app is hidden; editing pauses Core via CSS.
document.addEventListener('visibilitychange',()=>document.body.classList.toggle('motion-paused',document.hidden));

ArchiveView.install(render);

EntriesView.install(render,toast);

RelationsView.install(render,page=>{active=page;render();},toast);

TimelineView.install(render,toast);

SimulationView.install(render,toast);

