(function(root){
 const range=180,linkedRange=110,linkLength=100;
 const pairKey=(a,b)=>JSON.stringify([a,b].sort());
 function create(entries,edges,saved={}){const nodes=entries.map((e,i)=>{const a=i*2.399963,r=32*Math.sqrt(i+1),p=saved[e.id];return {id:e.id,x:p?.x??600+Math.cos(a)*r,y:p?.y??400+Math.sin(a)*r,vx:0,vy:0,pinned:!!p?.pinned,degree:0};});const byId=new Map(nodes.map(n=>[n.id,n]));const links=edges.filter(([a,b])=>byId.has(a)&&byId.has(b));for(const [a,b] of links){byId.get(a).degree++;byId.get(b).degree++;}return {nodes,byId,links};}
 function step(sim,fixed=null){const {nodes,byId,links}=sim;const connected=new Set(links.map(([a,b])=>pairKey(a,b))),pulled=new Set();const nearest=new Map(nodes.map(n=>[n.id,Infinity]));const forces=new Map(nodes.map(n=>[n.id,{x:0,y:0}]));
 for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j];let dx=b.x-a.x,dy=b.y-a.y;if(Math.abs(dx)+Math.abs(dy)<.001){dx=.1;dy=.07;}const distance=Math.hypot(dx,dy);const cutoff=connected.has(pairKey(a.id,b.id))?linkedRange:range;if(distance>=cutoff)continue;nearest.set(a.id,Math.min(nearest.get(a.id),distance));nearest.set(b.id,Math.min(nearest.get(b.id),distance));const d=Math.max(12,distance),fade=Math.min(1,(cutoff-distance)/60),push=fade*650*(1+.65*a.degree)*(1+.65*b.degree)/(d*d);let fx=dx/d*push,fy=dy/d*push;if(Math.abs(dx)<94&&Math.abs(dy)<38){const overlapX=94-Math.abs(dx),overlapY=38-Math.abs(dy);if(overlapX<overlapY)fx+=Math.sign(dx)*overlapX*.045;else fy+=Math.sign(dy)*overlapY*.045;}const fa=forces.get(a.id),fb=forces.get(b.id);fa.x-=fx;fa.y-=fy;fb.x+=fx;fb.y+=fy;}
 // Attraction belongs only to explicit edges; unrelated nodes have no attraction.
 for(const [a,b] of links){const p=byId.get(a),q=byId.get(b),dx=q.x-p.x,dy=q.y-p.y,d=Math.hypot(dx,dy);if(d<=linkLength)continue;const pull=Math.min(3,(d-linkLength)*.018),fx=dx/d*pull,fy=dy/d*pull;forces.get(a).x+=fx;forces.get(a).y+=fy;forces.get(b).x-=fx;forces.get(b).y-=fy;pulled.add(a);pulled.add(b);}
 let speed=0;for(const n of nodes){if((fixed instanceof Set?fixed.has(n.id):n.id===fixed)||n.pinned||(!pulled.has(n.id)&&nearest.get(n.id)>=range)){n.vx=n.vy=0;continue;}const f=forces.get(n.id);const damping=pulled.has(n.id)?.78:.35+.51*Math.min(1,(range-nearest.get(n.id))/60);n.vx=(n.vx+f.x)*damping;n.vy=(n.vy+f.y)*damping;if(Math.hypot(n.vx,n.vy)<.015&&Math.hypot(f.x,f.y)<.001){n.vx=n.vy=0;}const v=Math.hypot(n.vx,n.vy);if(v>7){n.vx*=7/v;n.vy*=7/v;}n.x+=n.vx;n.y+=n.vy;speed=Math.max(speed,Math.hypot(n.vx,n.vy));}return speed;
 }
 const api={create,step,range,linkedRange,linkLength};if(typeof module!=='undefined')module.exports=api;else root.RelationForce=api;
})(globalThis);
